this = {}; _fn = {}   -- This file was generated by Code12 from "TestProgram.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
    this.xOrigin = 0
    this.dot = nil; 
    
    
        
        
    
    
    function _fn.start()
        
        this.dot = ct.circle(50, 50, 10)
        local t = ct.rect(25, 75, 10, 50)
        t.group = "targets"
        t = ct.rect(75, 75, 10, 50)
        t.group = "targets"
        t = ct.text("Hello", 50, 25, 10)
        t.group = "targets"
    end
    
    function _fn.update()
        
        if ct.keyPressed("right") then
            
            this.xOrigin = this.xOrigin + (10)
            ct.setScreenOrigin(this.xOrigin, 0)
        
        elseif ct.keyPressed("left") then
            
            this.xOrigin = this.xOrigin - (10)
            ct.setScreenOrigin(this.xOrigin, 0)
        end
        
        if ct.charTyped("a") then
            this.dot.x = this.dot.x - 1; 
        elseif ct.charTyped("d") then
            this.dot.x = this.dot.x + 1; 
        elseif ct.charTyped("w") then
            this.dot.y = this.dot.y - 1; 
        elseif ct.charTyped("s") then
            this.dot.y = this.dot.y + 1; end
        
        local hit = this.dot:objectHitInGroup("targets")
        if hit ~= nil then
            hit:delete(); end
        
        local clicked = ct.objectClicked()
        if clicked ~= nil then
            clicked:delete(); end
        
    end
    
