this = {}; _fn = {}   -- This file was generated by Code12 from "CheckIndentationTest.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
    
    
    
    
    
    
    
    
    
    
    
    
        
        
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    function _fn.start()
        
        local x = 1
        local y = 2
        
        
        
        
        
        
        
        -- if statements
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        -- if-else statements
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        -- if-else if statements
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        -- if-else if-else statements
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        -- if-else if-else if-else statements
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        -- if-if-else statements
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        -- if-if-else if statements
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        -- for loops
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        -- while loops
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        -- do-while loops
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        -- multi-line variable declarations
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        
        -- multi-line variable initializations
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        -- multi-line function calls
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        -- multi-line array initializations
        -- -------------------------------------------------------------------------------------------
        
        
        
        
        
        
        
        
        
        
        ct.println("end of start function")
    end
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    -- Okay indentation
    -- ----------------------------------------------------------------
    this.a = 0; this.b = 0; 
    
    
    this.c = 0; this.d = 0; this.e = 0; this.f = 0; this.g = 0; 
    
    this.coins = nil; this.walls = nil; 
    this.LIMIT = 100
    this.arr = { 1, 2, 3, length = 3, default = 0 }
    this.arr2 = { length = 10, default = 0 }
    
    
    this.arr3 = { 1, 2, 3, length = 3, default = 0 }
    
    function _fn.areEqual(i, j)
        
        return i == j
    end
    
    
    function _fn.onMousePress(obj, x, y)
        
        -- if ( obj != null )
        -- 	ct.log( obj, ct.random( 1,
        -- 							100 ),
        -- 			x, y );
        
        ct.println("Mouse pressed")
    end
    
    
    
    function _fn.onMouseRelease(obj, x, y)
        
        -- int[] arr1 = { 1,
        -- 	   2, 
        -- 	   ct.random(1,
        -- 	   		2) };
        
        -- int[] arr2 = { 1,
        -- 			   2, 
        -- 			   ct.random( 1,
        -- 			              100 ),
        -- 			   4 };
        
        ct.println("Mouse released")
        
    end
    

