this = {}; _fn = {}   -- This file was generated by Code12 from "SimplePlatformer.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
    this.playerLeft = nil; 
    this.playerRight = nil; 
    this.platform = nil; 
    this.ground = nil; 
    
    this.gravity = -0.5
    
    this.onGround = true
    
    
    
        
        
    
    
    function _fn.start()
        
        local width = ct.getWidth()
        local height = ct.getHeight()
        
        this.ground = ct.line(0, height - 10, width, height - 10)
        this.platform = ct.rect(30, height - 20, 20, 20, "light blue")
        this.playerLeft = ct.image("stickmanleft.png", 10, height - 15, 10)
        this.playerLeft.visible = false
        this.playerRight = ct.image("stickmanright.png", 10, height - 15, 10)
        
        -- only one player visible at a time
        -- one facing left one right
        
    end
    
    function _fn.update()
        
        local height = ct.getHeight()
        --playerRight.ySpeed += gravity;
        
        
        
        
        if this.playerRight.y > (height - 20) or this.playerLeft.y > (height - 20) then
            
            this.onGround = true
        end
        
        if this.playerRight:hit(this.platform) or this.playerLeft:hit(this.platform) then
            
            this.onGround = true
        end
        
        _fn.bounce(this.playerRight)
        _fn.bounce(this.playerLeft)
        
    end
    
    function _fn.onKeyRelease(keyName)
        
        
    end
    
    function _fn.bounce(obj)
        
        if obj.x > ct.getWidth() then
            obj.x = 0; end
        if obj.x < 0 then
            obj.x = ct.getWidth(); end
        if obj.y > ct.getHeight() then
            obj.y = obj.y - 1; end
        if obj.y < 0 then
            obj.y = obj.y + 1; end
    end
    
    
    
    function _fn.onKeyPress(keyName)
        
        
        if (keyName == "space") then
            
            local s = 5; while s > 0 do
                
                this.playerRight.ySpeed = -s
                if this.playerRight.y < 30 then
                    
                    ct.println("is this executing")
                    this.playerRight.ySpeed = -this.playerRight.ySpeed
                end
            s = s - 1; end
            
        end
        
        if (keyName == "left") then
            
            this.playerRight.visible = false
            this.playerLeft.visible = true
            this.playerRight.xSpeed = this.playerRight.xSpeed - (1)
            this.playerLeft.xSpeed = this.playerLeft.xSpeed - (1)
        end
        
        if (keyName == "right") then
            
            this.playerRight.visible = true
            this.playerLeft.visible = false
            this.playerRight.xSpeed = this.playerRight.xSpeed + (1)
            this.playerLeft.xSpeed = this.playerLeft.xSpeed + (1)
        end
        
        
        -- a distance from top of players y value minus 
        -- double distance = ct.distance( player.x, player.y, player.x, player.y - 10)
        -- set jump player y speed to negative
        -- if ( player.y > player.y + d)
        
        
        
    end


