this = {}; _fn = {}   -- This file was generated by Code12 from "TestProgram.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
    
    
        
        
    
    
    function _fn.start()
        
        ct.println(3e)
    end
    
    function _fn.update()
        
    end
    
