this = {}; _fn = {}   -- This file was generated by Code12 from "Spaceship.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
--    onKeyRelease()
--    onMousePress()
--    onMouseRelease()
-- Game level: 8. If-else




    
    this.bg = nil; 
    this.topBg = nil; 
    this.asteroid = nil; 
    this.spaceship = nil; 
    this.spaceshipWreck = nil; 
    this.rayGun = nil; 
    this.flame = nil; 
    this.blackHole = nil; 
    this.beginText = nil; 
    this.traveledText = nil; 
    this.lightYears = 0
    this.hit = 0; 
    this.collision = 0; 
    
    
        
        
    
    
    function _fn.start()
        
        local width = ct.getWidth()
        local height = ct.getHeight()
        
        ct.setTitle("Space Adventure 9000")
        -- Color any space not covered by the background image
        ct.setBackColor("black")
        
        -- Background one fills screen initally
        this.bg = ct.image("seamless_tileable_nebula.jpg", width / 2, height / 2, width)
        this.bg.height = height
        
        -- Second background is off of screen upwards
        this.topBg = ct.image("seamless_tileable_nebula.jpg", width / 2, height / 2 - height, width)
        this.topBg.height = height
        this.beginText = ct.text("Click on the spaceship to begin!", width / 2, height - 40, 4, "white")
        this.traveledText = ct.text("Light years traveled: "..tostring(0), 15, 5, 3, "white")
        
        this.asteroid = ct.image("asteroid.png", ct.random(10, 100), ct.random(10, 100), 10)
        
        this.spaceship = ct.image("spacecraft.png", width / 2, height - 10, 5)
        this.spaceship:setLayer(2)
        
        this.flame = ct.image("transparent-flame.png", this.spaceship.x, this.spaceship.y + this.spaceship.height / 2, 5)
        this.flame.visible = false
        
        this.rayGun = ct.circle(this.spaceship.x, this.spaceship.y - 2, 1, "red")
        
    end
    
    function _fn.update()
        
        this.flame.clickable = false
        this.asteroid.clickable = false
        this.bg.clickable = false
        this.rayGun.visible = false
        ct.setTitle(tostring(ct.toInt(60 - (ct.getTimer() / 1000.0))).." seconds until the black hole")
        -- Set the initial background down
        this.bg.ySpeed = 0.5
        -- Set the top background moving down
        this.topBg.ySpeed = 0.5
        
        -- Once the utmost point of the top background reaches the game window 
        if (this.topBg.y - this.topBg.height / 2) >= 0 then
            
            -- Subtract one background height from both of the background's vertical positions 
            this.topBg.y = this.topBg.y - (ct.getHeight())
            this.bg.y = this.bg.y - (ct.getHeight())
        end
        
        -- If ray gun goes off screen, put it back in its original position
        if this.rayGun.y < 0 then
            this.rayGun = ct.circle(this.spaceship.x, this.spaceship.y - 2, 1, "red"); end
        
        
        -- If the spaceship is moving upwards and the current time is less than one minute (basically, while game is active)
        if this.spaceship.ySpeed ~= 0 and ct.getTimer() / 1000.0 < 60 then
            
            -- If spaceship is higher than or equal to than asteroid, relative to the top of the game window, re-draw it
            if this.spaceship.y <= this.asteroid.y then
                
                this.asteroid:delete()
                this.asteroid = ct.image("asteroid.png", ct.random(10, 100), ct.random(ct.toInt(this.spaceship.y) - 10, 100), ct.random(10, 30))
            end
            
            
            -- Increase amount of light years traveled
            this.traveledText:delete()
            this.lightYears = this.lightYears + (0.5)
            this.traveledText = ct.text("Light years traveled: "..tostring(this.lightYears), 15, 5, 3, "white")
            
            -- Move the ray gun along with the spaceship
            this.rayGun.y = this.spaceship.y
            
            -- If the spaceship goes off screen, set it back to starting position
            --if ( spaceship.y < 0 )
            --spaceship.y = ct.getHeight() - 10;
            
        end
        -- Check to see if the ray gun hit an asteroid
        this.hit = ct.distance(this.rayGun.x, this.rayGun.y, this.asteroid.x, this.asteroid.y)
        if this.hit < 5 then
            
            this.asteroid:delete()
            this.asteroid = ct.image("asteroid.png", ct.random(10, 100), ct.random(ct.toInt(this.spaceship.y), 100), ct.random(10, 30))
        end
        
        
        -- Check for collisions with spaceship and asteroid)        
        this.collision = ct.distance(this.spaceship.x, this.spaceship.y, this.asteroid.x, this.asteroid.y)
        
        if this.collision < 5 then
            
            ct.sound("explosion.wav")
            this.blackHole = ct.image("seamless_tileable_nebula.jpg", ct.getWidth() / 2, ct.getHeight() / 2, ct.getWidth())
            this.blackHole.height = ct.getHeight()
            this.spaceshipWreck = ct.image("spacecraft-wreck.png", this.spaceship.x, this.spaceship.y, this.spaceship.width + 10)
            this.spaceship.ySpeed = 0
            this.asteroid:delete()
            this.traveledText:delete()
            --ct.text("Game over! You traveled: " + lightYears + " light years.", ct.getWidth() /2, ct.getHeight() - 10, 5,"white" );
        end
        
        --Enter the black hole after 1 minute
        if ct.getTimer() / 1000.0 > 60 then
            
            this.blackHole = ct.image("a0620-00.jpg", ct.getWidth() / 2, ct.getHeight() / 2, ct.getWidth())
            this.blackHole.height = ct.getHeight()
            
            -- A circle GameObj serves as the origin which all game objs "gravitate" towards
            local origin = ct.circle(ct.getWidth() / 2 + 10, ct.getHeight() / 2, 10, "black")
            this.spaceship.xSpeed = (origin.x - this.spaceship.x) / 15.0
            this.spaceship.ySpeed = (origin.y - this.spaceship.y) / 15.0
            this.asteroid.xSpeed = (origin.x - this.asteroid.x) / 15.0
            this.asteroid.ySpeed = (origin.y - this.asteroid.y) / 15.0
            this.traveledText:delete()
            ct.setTitle("Game over")
            ct.text("Game over! You traveled: "..tostring(this.lightYears).." light years.", ct.getWidth() / 2, ct.getHeight() - 20, 5, "white")
            
        end
        
    end
    
    function _fn.onKeyPress(keyName)
        
        if (keyName == "right") and this.spaceship.x < ct.getWidth() then
            
            this.spaceship.x = this.spaceship.x + (5)
            this.rayGun.x = this.rayGun.x + (5)
            if this.spaceship.ySpeed ~= 0 then
                this.flame.x = this.flame.x + (5); end
        
        elseif (keyName == "left") and this.spaceship.x > 0 then
            
            this.spaceship.x = this.spaceship.x - (5)
            this.rayGun.x = this.rayGun.x - (5)
            if this.spaceship.ySpeed ~= 0 then
                this.flame.x = this.flame.x - (5); end
        end
        
    end
    
    function _fn.onKeyRelease(keyName)
        
        -- Shoot from spaceship
        if (keyName == "up") then
            
            this.rayGun.ySpeed = -2
            ct.sound("raygun.wav")
        end
    end
    
    function _fn.onMousePress(obj, x, y)
        
        -- If spaceship is clicked on, flame is "active" and both move upward
        if obj == this.spaceship then
            
            this.spaceship.ySpeed = this.spaceship.ySpeed - (0.075)
            this.flame = ct.image("transparent-flame.png", this.spaceship.x, this.spaceship.y + this.spaceship.height / 2, 5)
            this.flame.visible = true
            this.flame.ySpeed = this.spaceship.ySpeed
            ct.sound("spaceship-engine-short.wav")
            this.beginText:delete()
            
        end
    end
    
    function _fn.onMouseRelease(obj, x, y)
        
        -- When nothing is being clicked,
        -- there is no movement ( besides the background )
        if obj ~= nil then
            
            this.spaceship.ySpeed = 0
            this.flame:delete()
        end
    end
    
