this = {}; _fn = {}   -- This file was generated by Code12 from "PattyoRama.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
    this.krabbyPatty = nil; this.roguePatty = nil; this.pipe = nil; this.play = nil; this.playText = nil; this.scoreText = nil; 
    this.score = 0
    
    
        
        
    
    
    function _fn.start()
        
        ct.setTitle("PATTY-O-RAMA!")
        
        --win screen
        ct.setScreen("win")
        ct.setBackImage("krabs.png")
        local winner = ct.text("Great job Matey!", 50, 10, 10, "red")
        
        --end screen
        ct.setScreen("end")
        ct.setBackColor("red")
        local _end = ct.text("You're Fired!!!!!", 50, 50, 10, "black")
        
        --Game screen
        ct.setScreen("game")
        local gameScreen = ct.image("kitchen.jpg", ct.getWidth() / 2, ct.getHeight() / 2, ct.getWidth())
        gameScreen.height = ct.getHeight()
        
        this.pipe = ct.image("chute.png", 60, 1, 60)
        this.scoreText = ct.text("Order completion: 0 / 5 Krabby Patties", 40, 95, 5, "yellow")
        
        --Start screen
        ct.setScreen("start")
        ct.setBackImage("kk.jpg")
        this.play = ct.circle(75, 15, 30, "yellow")
        this.play:setLineColor("yellow")
        this.playText = ct.text("PLAY", 75, 15, 10, "black")
        local directions = ct.text("Complete an order of 5 krabby patties, watch out for the spoiled ones!", 50, 96, 3.2, "white")
    end
    
    function _fn.update()
        
        
        this.play.clickable = true
        if this.play:clicked() then
            ct.setScreen("game"); end
        
        local screen = ct.getScreen()
        if (screen == "game") and ct.random(1, 20) == 1 then
            
            -- random position for krabby patties
            local X = ct.random(40, 80)
            local Y = ct.random(35, 45)
            
            this.krabbyPatty = ct.image("krabbyPatty.png", X, Y, 20)
            this.krabbyPatty.clickable = true
            this.krabbyPatty.ySpeed = 0.7
        end
        if (screen == "game") and ct.random(1, 30) == 1 then
            
            -- random position or rogue patties
            local x = ct.random(40, 80)
            local y = ct.random(40, 45)
            
            this.roguePatty = ct.image("nastyPatty.png", x, y, 25)
            this.roguePatty.clickable = true
            this.roguePatty.ySpeed = 0.7
        end
        --checks if won              
        if this.score == 5 then
            
            ct.setScreen("win")
        end
        --checks if failed
        if this.score <= -2 then
            
            ct.sound("buzzer.wav")
            ct.setScreen("end")
        end
    end
    
    function _fn.onMousePress(obj, x, y)
        
        local screen = ct.getScreen()
        --deletes whichever object gets clicked on 
        if obj ~= nil then
            
            obj:delete()
            
            if obj == this.krabbyPatty then
                
                this.score = this.score + 1
                this.scoreText:setText("Order Completion:  " .. this.score .. "/5 Krabby Patties")
            end
            if obj == this.roguePatty then
                
                if this.score > 1 then
                    this.score = this.score - 1; end
                this.scoreText:setText((3 + this.score) .. " away from getting fired!!! ")
            end
        end
    end
