this = {}; _fn = {}   -- This file was generated by Code12 from "MainProgram.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
    
        
        
    
    this.frameCount = 0; 
    this.image = nil; 
    
    function _fn.start()
        
        this.frameCount = 1
        local pixelsPerUnit = ct.getPixelsPerUnit()
        local width = 225 / pixelsPerUnit
        local height = 224 / pixelsPerUnit
        
        this.image = ct.image("background.png", width, height, 100)
        this.image.xSpeed = 1
    end
    
    function _fn.update()
        
        this.frameCount = this.frameCount + 1
        if this.image.width > 10 and this.frameCount % 10 == 1 then
            
            this.image.width = this.image.width - (1)
            this.image.height = this.image.height - (1)
        end
        if this.image.x > 100 then
            
            this.image.x = 0
        end
    end
