this = {}; _fn = {}   -- This file was generated by Code12 from "TestProgram.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
        
        
    
    
    function _fn.start()
        
    end
    
    function _fn.onKeyPress(keyName)
        
        if (keyName == "b") then
            ct.setBackImage("background.png"); end
    end
