this = {}; _fn = {}   -- This file was generated by Code12 from "errorTest.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')


this.testCheckJava = true


this.constant = 1   --not an error


function _fn.start()


	if this.testCheckJava then

		_fn.testCheckJava()
	end
end


































function _fn.testCheckJava()







	local test = "한글"
end
