this = {}; _fn = {}   -- This file was generated by Code12 from "dataTypeTest.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
    
        
        
    
    
    function _fn.start()
        
        local i = 2147483647   --this is the maximum value of a Java int
        local negI = -2147483648   --this is the minimum value of a Java int
        
        local x = 2147483648   --this is the allowed in Code12 and not in Java
        local negX = -2147483649   --this is the allowed in Code12 and not in Java
        
        i = i + 1   --the maximum int value plus 1
        negI = negI - 1   --the minimum int value minus 1
        
        local doubleI = i * 2
        
        ct.println("Maximum int :"..tostring(i))   --this overflows and prints the minimum int value in JGrasp and prints 2147483648 in Code12
        ct.println("Minimum int :"..tostring(negI))   --this overflows and prints the maximum int value in JGrasp and prints -2147483649 in Code12
        ct.println("Double max int:"..tostring(doubleI))
        
        local y = 1.7976931348623157 * math.pow(10, 308)
        ct.println("Largest Double: "..tostring(y))
        
        local yplus1 = y + 1
        ct.println("Largest Double Plus 1: "..tostring(yplus1))
        
        ct.print("Difference between them: "..tostring((yplus1 - y)))
        
        local t = false; 
        local f = false
        
    end
    
    function _fn.test()
        
        
    end

