this = {}; _fn = {}   -- This file was generated by Code12 from "HelloWorld.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
    function _fn.start()
        
        ct.println("Hello World!")
    end

