this = {}; _fn = {}   -- This file was generated by Code12 from "MainProgram.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')

	ct.println("Hey")
	-- int x = 4;
	ct.circle(50, 30, 10)
end
