this = {}; _fn = {}   -- This file was generated by Code12 from "MainProgram.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
    -- GameObj c = ct.circle(0, 0, 0);
    
    
        
        
    
    
    function _fn.start()
        
        local i = 4
        local ratios = { length = 10 }
        local scores = { 2, 3, length = 2 }
        local rects = _fn.makeRects()
        rects = _fn.makeRects()
        _fn.foo("hey")
        rects[1+(1)]:setFillColor("red")
        ct.logm("I created", rects[1+(1)])
    end
    
    function _fn.makeRects()
        
        
        local a = { ct.rect(50, 50, 75, 25), ct.rect(50, 25, 50, 20), length = 2 }
        return a
    end
    
    function _fn.foo(s)
        
        ct.println(math.min(3.4, 2.1))
        if (s == "hey") then
            ct.println("Foo! " .. string.len(s)); end
    end
