this = {}; _fn = {}   -- This file was generated by Code12 from "Towers.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
    this.base = nil; 
    this.pole1 = nil; 
    this.pole1box = nil; 
    this.pole2 = nil; 
    this.pole2box = nil; 
    this.pole3 = nil; 
    this.pole3box = nil; 
    
    this.small = nil; 
    this.medium = nil; 
    this.large = nil; 
    
    
        
        
    
    
    function _fn.start()
        
        -- Initial base 
        this.base = ct.rect(ct.getWidth() / 2, ct.getHeight() / 2 + 20, 70, 5, "gray")
        this.base.lineWidth = 5
        this.pole1 = ct.rect(this.base.x / 3, this.base.y - 7.5, 3, 20, "gray")
        this.pole1.lineWidth = 3
        this.pole1box = ct.rect(this.pole1.x, this.pole1.y, this.pole1.width, ct.getHeight())
        this.pole2 = ct.rect(this.base.x, this.base.y - 7.5, 3, 20, "gray")
        this.pole2.lineWidth = 3
        this.pole3 = ct.rect(this.base.x + 34, this.base.y - 7.5, 3, 20, "gray")
        this.pole3.lineWidth = 3
        
        this.small = ct.circle(this.pole2.x, this.pole2.y - 9, 10, "blue")
        this.small.height = 3
        this.small.lineWidth = 3
        this.small:setLineColor("dark blue")
        
        this.medium = ct.circle(this.pole2.x, this.pole2.y - 5, 15, "green")
        this.medium.height = 5
        this.medium.lineWidth = 3
        this.medium:setLineColor("dark green")
        
        this.large = ct.circle(this.pole2.x, this.pole2.y + 1, 18, "red")
        this.large.height = 7
        this.large.lineWidth = 3
        this.large:setLineColor("dark red")
        
        
    end
    
    function _fn.update()
        
        this.small.clickable = true
        this.medium.clickable = true
        this.large.clickable = true
        
        
    end
    
    -- Helper function to determine if object is under another
    function _fn.moveDiskToPole(obj)
        
        if this.small:hit(this.pole1box) then
            
            this.small.ySpeed = 1
            if this.small.y > this.pole1.y then
                this.small.ySpeed = 0; end
        end
        
        
        
    end
    
    function _fn.onMousePress(obj, x, y)
        
        
    end
    
    function _fn.onMouseDrag(obj, x, y)
        
        if obj == this.small then
            
            this.small.x = x
            this.small.y = y
            _fn.moveDiskToPole(this.small)
        end
        
    end
    
