this = {}; _fn = {}   -- This file was generated by Code12 from "level1.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
    
    
    
    
        
        
    
    
    function _fn.start()
        
        --draws the background
        ct.setBackImage("background-day.png")
        
        --sets the height of the sceen to match the height of the background
        ct.setHeight(128)
        
        --draws the bird
        ct.image("yellowbird-downflap.png", 50, 50, 10)
        
        --draws the count
        ct.image("0.png", 50, 18, 5)
        
        --draws the ground
        ct.image("base.png", 20, 122, 40)
        ct.image("base.png", 60, 122, 40)
        ct.image("base.png", 100, 122, 40)
    end
