this = {}; _fn = {}   -- This file was generated by Code12 from "StructureTest.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')


this.fish = nil; this.ball = nil; this.bigBall = nil

this.count = 0; this.total = 0
this.gameOver = false


this.LIMIT = 120 + 4
this.speed = 0.3
this.frameCount = 0
this.newCount = this.frameCount + 2 *  -this.frameCount
this.str = "Testing"






function _fn.start()

	local X = 50
	local y = 0
	y = X
	this.ball = ct.circle(X, y, 30)
	this.ball:setFillColor("blue")
	this.frameCount = _fn.foo(this.LIMIT, this.speed * 2)
	ct.println("Program started")
end

function _fn.foo()


	i = 8
	return 0
end

function _fn.test()

	if i < 0 then
		return i + 1
	else

		i = i + (3)
		d = d * (2)
	end

	if d == i then
		d = i
	elseif d < i then
		d =  -i
	else
		i = 0
	end
	repeat
		i = i + 1
	until not (i < 0)

	d = 13

	while i > 10 do

		i = i - 1
		i = i + 1
	end

	d = 24
	d = d * (1.0 - ct.toInt(math.pow(d / d, i)))

	local j = i; while j < 10 do

		d = d + (i)
		i = i - 1; j = j + 1
	end

	i = ct.toInt(math.pi) * _fn.foo(1, 3.1)

	return 0
end

function _fn.update()

	_fn.moveBall(false)
end

function _fn.onMousePress()
end










function _fn.moveBall()

	this.ball.x = this.ball.x + 1
	if wrap then

		local checked = true
		if this.ball.x > 100 then
			this.ball.x = 0
		end
	end; return this.ball.x
end

function _fn.makeCircles()

	local circles = { length = 10, default = nil }
	for _, c in ipairs(circles) do
		c:setFillColor("black")
	end; local scores = { 10, 20, 30, }
	return circles
end
