-- Code12 API tables
-- *** DO NOT EDIT *** This file is generated by the Make API tool.

return {

["ct"] = {
    fields = {
    },
    methods = {
        ["ct.print"] = { vt = false, params = {{ name = value, vt = nil}} },
        ["ct.println"] = { vt = false, min = 0, params = {{ name = value, vt = nil}} },
        ["ct.log"] = { vt = false, params = {{ name = values, vt = nil}} },
        ["ct.logm"] = { vt = false, params = {{ name = message, vt = "String"},{ name = values, vt = nil}} },
        ["ct.inputInt"] = { vt = 0, params = {{ name = message, vt = "String"}} },
        ["ct.inputNumber"] = { vt = 1, params = {{ name = message, vt = "String"}} },
        ["ct.inputBoolean"] = { vt = true, params = {{ name = message, vt = "String"}} },
        ["ct.inputString"] = { vt = "String", params = {{ name = message, vt = "String"}} },
        ["ct.setTitle"] = { vt = false, params = {{ name = title, vt = "String"}} },
        ["ct.setHeight"] = { vt = false, params = {{ name = height, vt = 1}} },
        ["ct.getWidth"] = { vt = 1, params = {} },
        ["ct.getHeight"] = { vt = 1, params = {} },
        ["ct.getPixelsPerUnit"] = { vt = 1, params = {} },
        ["ct.getScreen"] = { vt = "String", params = {} },
        ["ct.setScreen"] = { vt = false, params = {{ name = name, vt = "String"}} },
        ["ct.clearScreen"] = { vt = false, params = {} },
        ["ct.clearGroup"] = { vt = false, params = {{ name = group, vt = "String"}} },
        ["ct.setBackColor"] = { vt = false, params = {{ name = color, vt = "String"}} },
        ["ct.setBackColorRGB"] = { vt = false, params = {{ name = red, vt = 0},{ name = green, vt = 0},{ name = blue, vt = 0}} },
        ["ct.setBackImage"] = { vt = false, params = {{ name = filename, vt = "String"}} },
        ["ct.circle"] = { vt = "GameObj", min = 3, params = {{ name = x, vt = 1},{ name = y, vt = 1},{ name = diameter, vt = 1},{ name = color, vt = "String"}} },
        ["ct.rect"] = { vt = "GameObj", min = 4, params = {{ name = x, vt = 1},{ name = y, vt = 1},{ name = width, vt = 1},{ name = height, vt = 1},{ name = color, vt = "String"}} },
        ["ct.line"] = { vt = "GameObj", min = 4, params = {{ name = x1, vt = 1},{ name = y1, vt = 1},{ name = x2, vt = 1},{ name = y2, vt = 1},{ name = color, vt = "String"}} },
        ["ct.text"] = { vt = "GameObj", min = 4, params = {{ name = s, vt = "String"},{ name = x, vt = 1},{ name = y, vt = 1},{ name = height, vt = 1},{ name = color, vt = "String"}} },
        ["ct.image"] = { vt = "GameObj", params = {{ name = filename, vt = "String"},{ name = x, vt = 1},{ name = y, vt = 1},{ name = width, vt = 1}} },
        ["ct.clicked"] = { vt = true, params = {} },
        ["ct.clickX"] = { vt = 1, params = {} },
        ["ct.clickY"] = { vt = 1, params = {} },
        ["ct.keyPressed"] = { vt = true, params = {{ name = keyName, vt = "String"}} },
        ["ct.charTyped"] = { vt = true, params = {{ name = ch, vt = "String"}} },
        ["ct.sound"] = { vt = false, params = {{ name = filename, vt = "String"}} },
        ["ct.setSoundVolume"] = { vt = false, params = {{ name = volume, vt = 1}} },
        ["ct.random"] = { vt = 0, params = {{ name = min, vt = 0},{ name = max, vt = 0}} },
        ["ct.round"] = { vt = 1, min = 1, params = {{ name = d, vt = 1},{ name = numPlaces, vt = 0}} },
        ["ct.isError"] = { vt = true, params = {{ name = d, vt = 1}} },
        ["ct.distance"] = { vt = 1, params = {{ name = x1, vt = 1},{ name = y1, vt = 1},{ name = x2, vt = 1},{ name = y2, vt = 1}} },
        ["ct.getTimer"] = { vt = 0, params = {} },
        ["getVersion"] = { vt = 1, params = {} },
        ["ct.toDouble"] = { vt = 1, params = {{ name = i, vt = 0}} },
        ["ct.toInt"] = { vt = 0, params = {{ name = d, vt = 1}} },
        ["ct.parseInt"] = { vt = 0, params = {{ name = s, vt = "String"}} },
        ["ct.canParseInt"] = { vt = true, params = {{ name = s, vt = "String"}} },
        ["ct.parseNumber"] = { vt = 1, params = {{ name = s, vt = "String"}} },
        ["ct.canParseNumber"] = { vt = true, params = {{ name = s, vt = "String"}} },
        ["ct.formatDecimal"] = { vt = "String", min = 1, params = {{ name = d, vt = 1},{ name = numPlaces, vt = 0}} },
        ["ct.formatInt"] = { vt = "String", min = 1, params = {{ name = i, vt = 0},{ name = numDigits, vt = 0}} },
    }
},

["GameObj"] = {
    fields = {
        ["x"] = 1,
        ["y"] = 1,
        ["width"] = 1,
        ["height"] = 1,
        ["xSpeed"] = 1,
        ["ySpeed"] = 1,
        ["lineWidth"] = 0,
        ["visible"] = true,
        ["clickable"] = true,
        ["autoDelete"] = true,
        ["group"] = "String",
    },
    methods = {
        ["getType"] = { vt = "String", params = {} },
        ["getText"] = { vt = "String", params = {} },
        ["setText"] = { vt = false, params = {{ name = text, vt = "String"}} },
        ["toString"] = { vt = "String", params = {} },
        ["setSize"] = { vt = false, params = {{ name = width, vt = 1},{ name = height, vt = 1}} },
        ["align"] = { vt = false, min = 1, params = {{ name = alignment, vt = "String"},{ name = adjustY, vt = true}} },
        ["setFillColor"] = { vt = false, params = {{ name = color, vt = "String"}} },
        ["setFillColorRGB"] = { vt = false, params = {{ name = red, vt = 0},{ name = green, vt = 0},{ name = blue, vt = 0}} },
        ["setLineColor"] = { vt = false, params = {{ name = color, vt = "String"}} },
        ["setLineColorRGB"] = { vt = false, params = {{ name = red, vt = 0},{ name = green, vt = 0},{ name = blue, vt = 0}} },
        ["getLayer"] = { vt = 0, params = {} },
        ["setLayer"] = { vt = false, params = {{ name = layer, vt = 0}} },
        ["delete"] = { vt = false, params = {} },
        ["clicked"] = { vt = true, params = {} },
        ["containsPoint"] = { vt = true, params = {{ name = x, vt = 1},{ name = y, vt = 1}} },
        ["hit"] = { vt = true, params = {{ name = obj, vt = "GameObj"}} },
    }
},

["Math"] = {
    fields = {
        ["E"] = 1,
        ["PI"] = 1,
    },
    methods = {
        ["abs"] = { vt = 1, overloaded = true, params = {{ name = a, vt = 1}} },
        ["acos"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["asin"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["atan"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["atan2"] = { vt = 1, params = {{ name = y, vt = 1},{ name = x, vt = 1}} },
        ["ceil"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["cos"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["cosh"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["exp"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["floor"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["log"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["log10"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["max"] = { vt = 1, overloaded = true, params = {{ name = a, vt = 1},{ name = b, vt = 1}} },
        ["min"] = { vt = 1, overloaded = true, params = {{ name = a, vt = 1},{ name = b, vt = 1}} },
        ["pow"] = { vt = 1, params = {{ name = a, vt = 1},{ name = b, vt = 1}} },
        ["sin"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["sinh"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["sqrt"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["tan"] = { vt = 1, params = {{ name = a, vt = 1}} },
        ["tanh"] = { vt = 1, params = {{ name = a, vt = 1}} },
    }
},

["String"] = {
    fields = {
    },
    methods = {
        ["compareTo"] = { vt = 0, params = {{ name = str2, vt = "String"}} },
        ["equals"] = { vt = true, params = {{ name = str2, vt = "String"}} },
        ["indexOf"] = { vt = 0, params = {{ name = strFind, vt = "String"}} },
        ["length"] = { vt = 0, params = {} },
        ["substring"] = { vt = "String", min = 1, params = {{ name = beginIndex, vt = 0},{ name = endIndex, vt = 0}} },
        ["toLowerCase"] = { vt = "String", params = {} },
        ["toUpperCase"] = { vt = "String", params = {} },
        ["trim"] = { vt = "String", params = {} },
    }
},

["Code12Program"] = {
    fields = {
    },
    methods = {
        ["start"] = { vt = false, params = {} },
        ["update"] = { vt = false, params = {} },
        ["onMousePress"] = { vt = false, params = {{ name = obj, vt = "GameObj"},{ name = x, vt = 1},{ name = y, vt = 1}} },
        ["onMouseDrag"] = { vt = false, params = {{ name = obj, vt = "GameObj"},{ name = x, vt = 1},{ name = y, vt = 1}} },
        ["onMouseRelease"] = { vt = false, params = {{ name = obj, vt = "GameObj"},{ name = x, vt = 1},{ name = y, vt = 1}} },
        ["onKeyPress"] = { vt = false, params = {{ name = key, vt = "String"}} },
        ["onKeyRelease"] = { vt = false, params = {{ name = key, vt = "String"}} },
        ["onCharTyped"] = { vt = false, params = {{ name = ch, vt = "String"}} },
        ["onResize"] = { vt = false, params = {} },
    }
},

}
