this = {}; _fn = {}   -- This file was generated by Code12 from "MoreInputTesting.java"
package.path = package.path .. ';../../Desktop/Code12/?.lua;../../../Desktop/Code12/?.lua'
require('Code12.api')
this.colors = { "black", "white", "red", "green", "blue", "cyan", "magenta", "yellow", length = 8, default = nil }
this.speed = false; 
this.yourSpeed = 0; 


    
    
    
        
        
    
    
    function _fn.start()
        
        local number = ct.inputInt("Enter number of circles to be drawn")
        this.circles = { length = number, default = nil }
        local i = 0; while i < this.circles.length do
            
            ct.checkArrayIndex(this.circles, i); this.circles[1+(i)] = ct.circle(ct.random(0, ct.toInt(ct.getWidth())), ct.random(0, ct.toInt(ct.getHeight())), ct.random(1, 25))
            local j = 0; while j < this.colors.length do
                
                ct.indexArray(this.circles, i):setFillColor(ct.indexArray(this.colors, j))
            j = j + 1; end
        i = i + 1; end
        
        this.speed = ct.inputYesNo("Should they be set at a random speed?")
        if this.speed == false then
            
            this.yourSpeed = ct.inputInt("Enter your own speed")
        end
        
        
        
        
    end
    
    function _fn.update()
        
        if this.speed == true then
            
            local i = 0; while i < this.circles.length do
                
                ct.checkArrayIndex(this.circles, i); this.circles[1+(i)].xSpeed = ct.random(1, 5)
            i = i + 1; end
        
        else 
            
            local i = 0; while i < this.circles.length do
                
                ct.checkArrayIndex(this.circles, i); this.circles[1+(i)].xSpeed = this.yourSpeed
            i = i + 1; end
        end
        
        local i = 0; while i < this.circles.length do
            
            _fn.wrapAround(ct.indexArray(this.circles, i))
            ct.checkArrayIndex(this.circles, i); this.circles[1+(i)].clickable = true
        i = i + 1; end
        
    end
    
    function _fn.onMousePress(obj, x, y)
        
        local i = 0; while i < this.circles.length do
            
            if obj == ct.indexArray(this.circles, i) then
                ct.showAlert("You clicked on circle number "..tostring(i).."!"); end
        i = i + 1; end
    end
    
    function _fn.wrapAround(obj)
        
        if obj.x > ct.getWidth() then
            obj.x = 0; 
        elseif obj.y > ct.getHeight() then
            obj.y = 0; end
    end
    
